language: node_js
node_js:
  - "6.0"
script:
  - echo "Deploying!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token "1/sOTFWDEnZtlh3r32TxWEAAVNQQcUy16pR-U22r8WYZo"