language: node_js
node_js:
  - "node"
script:
  -
    
deploy:
  provider: firebase
  token:
    secure: "rliJswp+4pb6MEWI3JBzaPhHEYjsGh2gxQgqXNRtMU6V8VE0ZOzU3rSqZ1J/fdL4feAKWQLocn2Hb9qI+Ror2rJ9qHS8Xb6tm2kWs364umQIC42SI7h4baRAGPE80/U3OfTucKG4xeJY0U0i7HjF9C+2NfZCJaFmNJIMxKcXn+Bz3UVYG0vryph5+fX3kd5JblhUHdAUz+HAtLLqG1MnTebSEVRW0WQNe4CKBiSCLW7DHUoluncNCF86yPiw5XOp5BbiPoRGUjG84SCdWHGwC5ijM0KWk8G0lwi4RjBUr6kWD52mAhmSQQGP2lDwEJjKgFQJC7KZ1OZ2bg8XojMvTYVGEC97Vi6N2ttIRUVlVYEsZ3F+jtmhb8SDS7WZFLKw7LOFd/0oE3jNpEFb2+v63vntkwN7+MGG5NqSd6cLaXTUUfyU/7dCuuXNe2T3vEPR3+OTu9fcet9yHj85PVC8Y3zQcyvkyhsX7gzjD7Amb/s/3aGzs1iPzrtnFIpOmRBqIlTRluiyfB/oSqngDhKh0EhAe+xi14/w2X0y5ZzyX4pSo8eLybaZ/UhQjQFQ9bvp/k63RkQatYDV2GhqMQvGAzI7Xpz4yKfDN4YLOPD5ThQ7Cn8l3YTZK6X0bvi1cCsFKTzq7PfsmVDylVYMvdpTDKtMbgNvx8kBxG/QIks3+Bg="
  project: "Friends-cast"