language: node_js
node_js:
  - "node"
script:
  -

deploy:
  provider: firebase
  token:
    secure: "X64vEmBhno99jPB8haSbWiLh7V4g0LWznvX11opGfqnLUMAArL4LfyZ2kzGuw6Cg8NbNKKQjj5U1pYB57MTkH+taX4ojkqu9O7Sovrs6jMpE+ZF/b3HoQbpJmlllzM4DQYdOj2KuIzZ3oTxxjZzd14FOJsodaQTexXBpDGcK0Z7muhKMNMLpXMMcE/MNgAoWi6uwQhLBPpcjK3SbXzPXDQs4mPqaRPiX12QEhU/goXN7jSHVo/L/R47ar50eBsZ91vk8BM/mTI6LnD8wjTTH0TGinBU0Q90RPtqPAxxT0L9yuHyps/j+oqGHxC8oos+wGXUPmawJyBW6MF2ONyiB5DbRrJArA+2n0Y35HeN+mDikrYnO/skt3H5/WTKIrm/359AuKhv7Ue6wzInxrBmd3qmpebVEOsQ6Phqfgp/j9/R7z24ZCl1ELZ1sMlEK0UEzgkWUwnzOV3kgL+xqVHygrNBak28QQWWf7u/bxMjuMGzh0VehjTMd3D7SjG0DYQ2rPQf6FbuJYOK5+QN0DiMrl4fnp/3ofrUcdjX/aJ23QSxhijUcc/Amj760ZGSkJx2zrtva9HXkZITFLuTGBQgOINmYxDaTsbNrzDoe487HqWON4dUHafWBTmySPKh5o+GJDXtvkcM/fxwCboCY7lR1rLHxe7QWdi5Wsso2HbRcLTo="
  project: "FriendsCast"